import type { SuggestedJob } from "./types";

export const CURATED_JOBS_CATALOG: SuggestedJob[] = [
  {
    id: "job-stripe-01",
    company: "Stripe",
    role: "Senior Full Stack Engineer, Developer Platform",
    location: "San Francisco, CA (Hybrid)",
    salaryRange: "$175,000 - $225,000",
    source: "LinkedIn",
    portalUrl: "https://stripe.com/jobs/search",
    description: "Build delightful developer tooling, high-availability payment dashboards, and global API infrastructure using React, TypeScript, Node.js, and distributed microservices.",
    requiredSkills: ["TypeScript", "React", "Node.js", "REST APIs", "Distributed Systems", "PostgreSQL"],
    experienceLevel: "Senior (4+ YOE)",
    postedDate: "2 days ago",
  },
  {
    id: "job-openai-02",
    company: "OpenAI",
    role: "Frontend Platform Engineer, Model Applications",
    location: "San Francisco, CA",
    salaryRange: "$200,000 - $260,000",
    source: "Other",
    portalUrl: "https://openai.com/careers/search",
    description: "Design next-generation interactive AI interfaces, canvas canvases, real-time audio/streaming UI, and evaluation tools for frontier models.",
    requiredSkills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "OpenAI", "Real-time WebSockets"],
    experienceLevel: "Mid-Senior (3+ YOE)",
    postedDate: "1 day ago",
  },
  {
    id: "job-vercel-03",
    company: "Vercel",
    role: "Software Engineer, Core DX & Frameworks",
    location: "Remote (Worldwide)",
    salaryRange: "$165,000 - $205,000",
    source: "Ashby",
    portalUrl: "https://vercel.com/careers",
    description: "Empower millions of developers by optimizing edge execution, incremental builds, Next.js core pipelines, and React Server Components.",
    requiredSkills: ["TypeScript", "JavaScript", "React", "Next.js", "Git", "CI/CD"],
    experienceLevel: "Mid-Level (2+ YOE)",
    postedDate: "3 days ago",
  },
  {
    id: "job-airbnb-04",
    company: "Airbnb",
    role: "Lead Full Stack Software Engineer",
    location: "San Francisco, CA / Remote",
    salaryRange: "$185,000 - $235,000",
    source: "Greenhouse",
    portalUrl: "https://careers.airbnb.com/positions/",
    description: "Architect guest and host booking platforms with exceptional UI quality, GraphQL microservices, and high-concurrency payment processing.",
    requiredSkills: ["React", "TypeScript", "GraphQL", "Node.js", "AWS", "PostgreSQL"],
    experienceLevel: "Lead (5+ YOE)",
    postedDate: "4 days ago",
  },
  {
    id: "job-datadog-05",
    company: "Datadog",
    role: "Backend Systems & Telemetry Engineer",
    location: "New York, NY (Hybrid)",
    salaryRange: "$170,000 - $210,000",
    source: "Greenhouse",
    portalUrl: "https://www.datadoghq.com/careers/",
    description: "Scale high-throughput streaming pipelines processing petabytes of logs, traces, and metrics per second with low latency.",
    requiredSkills: ["Python", "C#", "Go", "Docker", "Kubernetes", "Redis", "Distributed Systems"],
    experienceLevel: "Senior (4+ YOE)",
    postedDate: "Just now",
  },
  {
    id: "job-uber-06",
    company: "Uber",
    role: "Software Engineer II, Real-Time Dispatch",
    location: "Seattle, WA / San Francisco, CA",
    salaryRange: "$160,000 - $198,000",
    source: "Workday",
    portalUrl: "https://www.uber.com/us/en/careers/list/",
    description: "Build mission-critical dispatch routing algorithms and driver-rider state machines handling billions of trips worldwide.",
    requiredSkills: ["TypeScript", "Node.js", "Python", "REST APIs", "Redis", "Microservices"],
    experienceLevel: "Mid-Level (3+ YOE)",
    postedDate: "2 days ago",
  },
  {
    id: "job-figma-07",
    company: "Figma",
    role: "Product Engineer, Design Systems & Canvas",
    location: "San Francisco, CA / Remote",
    salaryRange: "$180,000 - $230,000",
    source: "Lever",
    portalUrl: "https://www.figma.com/careers/",
    description: "Craft multiplayer canvas interactions, GPU-accelerated graphics rendering, and developer handoff capabilities.",
    requiredSkills: ["TypeScript", "React", "JavaScript", "WebSockets", "Canvas/WebGL"],
    experienceLevel: "Senior (4+ YOE)",
    postedDate: "5 days ago",
  },
  {
    id: "job-microsoft-08",
    company: "Microsoft",
    role: "Cloud Solutions Engineer, Azure & .NET Core",
    location: "Redmond, WA / Remote",
    salaryRange: "$155,000 - $190,000",
    source: "Workday",
    portalUrl: "https://careers.microsoft.com/",
    description: "Develop enterprise cloud backends and resilient distributed APIs using ASP.NET Core, C#, Azure Kubernetes, and SQL.",
    requiredSkills: ["C#", ".NET", "ASP.NET Core", "Azure", "PostgreSQL", "Docker"],
    experienceLevel: "Mid-Senior (3+ YOE)",
    postedDate: "3 days ago",
  },
];
